import { getServerSession } from 'next-auth';
import '../styles/globals.css'
import Header from './Header'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession();
  return (
    <html lang="en">
      <head/>   
      <body>
      <Header session={session}/> 
        {children}
      </body>
    </html>
  )
}
